server:
 port: 8085

spring:
 mail:
  properties:
   mail:
    smtp:
     starttls:
      enable: 'true'
     auth: 'true'
  host: smtp.gmail.com
  username: nahomhagos29@gmail.com
  password: zyozjpumirkseurl
  port: '587'
